project_id = "yiqynvkihvrjiwuwibep"

[functions.process-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.get-mp-public-key]
verify_jwt = false

[functions.fetch-news]
verify_jwt = false
